In [3]:
%pip install matplotlib
%pip install seaborn
%pip install mysql-connector-python
%pip install sqlalchemy

Requirement already satisfied: matplotlib in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib) (2.4.5)
Requirement already satisfied: packaging>=20.0 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: seaborn in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from seaborn) (2.4.5)
Requirement already satisfied: pandas>=1.2 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from seaborn) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: mysql-connector-python in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (9.7.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: sqlalchemy in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\Users\anaka\OneDrive\Documents\GitHub\proyecto_mod_2\.venv\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import mysql.connector

from sqlalchemy import create_engine

In [5]:
tracks = pd.read_csv('../data/tracks.csv')

artists = pd.read_csv('../data/artists.csv')

In [6]:
print(tracks.shape)
print(artists.shape)

(586672, 20)
(1162095, 5)

In [7]:
tracks.head()

,id,name,popularity,duration_ms,explicit,artists,id_artists,release_date,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,35iwgR4jXetI318WEWsa1Q,Carve,6,126903,0,['Uli'],['45tIt06XoI0Iio4LBEVpls'],1922-02-22,0.645,0.4450,0,-13.338,1,0.4510,0.674,0.7440,0.151,0.127,104.851,3
1,021ht4sdgPcrDgSk7JTbKY,Capítulo 2.16 - Banquero Anarquista,0,98200,0,['Fernando Pessoa'],['14jtPCOoNZwquk5wd9DxrY'],1922-06-01,0.695,0.2630,0,-22.136,1,0.9570,0.797,0.0000,0.148,0.655,102.009,1
2,07A5yehtSnoedViJAZkNnc,Vivo para Quererte - Remasterizado,0,181640,0,['Ignacio Corsini'],['5LiOoJbxVSAMkBS2fUm3X2'],1922-03-21,0.434,0.1770,1,-21.180,1,0.0512,0.994,0.0218,0.212,0.457,130.418,5
3,08FmqUhxtyLTn6pAh6bk45,El Prisionero - Remasterizado,0,176907,0,['Ignacio Corsini'],['5LiOoJbxVSAMkBS2fUm3X2'],1922-03-21,0.321,0.0946,7,-27.961,1,0.0504,0.995,0.9180,0.104,0.397,169.980,3
4,08y9GfoqCWfOGsKdwojr5e,Lady of the Evening,0,163080,0,['Dick Haymes'],['3BiJGZsyX9sJchTqcSA7Su'],1922,0.402,0.1580,3,-16.900,0,0.0390,0.989,0.1300,0.311,0.196,103.220,4

In [8]:
artists.head()

,id,followers,genres,name,popularity
0,0DheY5irMjBUeLybbCUEZ2,0.0,[],Armid & Amir Zare Pashai feat. Sara Rouzbehani,0
1,0DlhY15l3wsrnlfGio2bjU,5.0,[],ปูนา ภาวิณี,0
2,0DmRESX2JknGPQyO15yxg7,0.0,[],Sadaa,0
3,0DmhnbHjm1qw6NCYPeZNgJ,0.0,[],Tra'gruda,0
4,0Dn11fWM7vHQ3rinvWEl4E,2.0,[],Ioannis Panoutsopoulos,0

In [9]:
tracks = tracks.sample(
    50000,
    random_state=42
)

In [10]:
print(tracks.shape)

(50000, 20)

In [11]:
tracks = tracks.drop_duplicates()

artists = artists.drop_duplicates()

In [12]:
tracks['release_date'] = pd.to_datetime(
    tracks['release_date'],
    format='mixed',
    errors='coerce'
)

In [13]:
tracks['release_year'] = (
    tracks['release_date']
    .dt.year
)

In [14]:
tracks[['release_date', 'release_year']].head()

       release_date  release_year
241517   1985-01-01          1985
444213   2017-08-25          2017
106480   1992-01-01          1992
141137   1969-01-01          1969
586550   2015-12-25          2015

In [15]:
tracks.isnull().sum()

id                  0
name                4
popularity          0
duration_ms         0
explicit            0
artists             0
id_artists          0
release_date        0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
release_year        0
dtype: int64

In [16]:
tracks = tracks.dropna(
    subset=['release_year']
)

In [17]:
tracks_db = tracks.head(5000).copy()

artists_db = artists.head(5000).copy()

In [18]:
print(tracks_db.shape)
print(artists_db.shape)

(5000, 21)
(5000, 5)

In [19]:
artists_clean = artists_db[[
    'id',
    'name'
]].copy()

In [21]:
artists_clean.columns = [
    'artist_id',
    'artist_name'
]

In [22]:
artists_clean = (
    artists_clean
    .drop_duplicates()
    .dropna()
)

In [23]:
artists_clean.head()

                artist_id                                     artist_name
0  0DheY5irMjBUeLybbCUEZ2  Armid & Amir Zare Pashai feat. Sara Rouzbehani
1  0DlhY15l3wsrnlfGio2bjU                                     ปูนา ภาวิณี
2  0DmRESX2JknGPQyO15yxg7                                           Sadaa
3  0DmhnbHjm1qw6NCYPeZNgJ                                       Tra'gruda
4  0Dn11fWM7vHQ3rinvWEl4E                          Ioannis Panoutsopoulos

In [ ]:
tracks_db['artist_id'] = (
    tracks_db['id_artists']
    .astype(str)
    .str.split(',')
    .str[0]
    .str.replace(r"[\"\'\[\] ]", "", regex=True)
)

In [25]:
tracks_clean = tracks_db[[
    'id',
    'name',
    'artist_id',
    'release_year',
    'popularity',
    'danceability',
    'energy',
    'valence',
    'acousticness',
    'duration_ms',
    'tempo'
]].copy()

In [26]:
tracks_clean.columns = [
    'track_id',
    'track_name',
    'artist_id',
    'release_year',
    'popularity',
    'danceability',
    'energy',
    'valence',
    'acousticness',
    'duration_ms',
    'tempo'
]

In [27]:
tracks_clean = (
    tracks_clean
    .drop_duplicates()
    .dropna()
)

In [28]:
tracks_clean.head()

,track_id,track_name,artist_id,release_year,popularity,danceability,energy,valence,acousticness,duration_ms,tempo
241517,0rTUAMd7huYjda84aceuzl,Дети проходных дворов,2jkl2xJVm71azWAgZKyf42,1985,21,0.890,0.6680,0.942,0.570,105015,137.934
444213,4bMy8NjgkVHize43OSrChu,95,7jLSEPYCYQ5ssWU3BICqrW,2017,37,0.663,0.5510,0.339,0.697,234800,128.992
106480,4X1xn2bjxlaLbx6o3jSEXj,As almal ver is,4utxbudXUuseiCfVJ0B2xM,1992,10,0.376,0.0979,0.236,0.485,147733,90.290
141137,3ZwzDf7V1xlAS9WWuviqIm,"Il tuo mondo (Nono, dobri moj nono)",2r4iOKmxTQU9s361Yt3gq1,1969,29,0.565,0.3270,0.556,0.781,194373,103.256
586550,712Hktc9DnU5u9uOSn1q1Y,Bazaar - Official Sunburn Goa 2015 Anthem,"2wX6xSig4Rig5kZU6ePlWe', '6S3KljEiIOWoLMUyZrkQUc",2015,55,0.582,0.9790,0.196,0.125,172500,128.010

In [29]:
from sqlalchemy import create_engine

DATABASE_URL = (
    "mysql+pymysql://"
    "DocBxbiNM1cbnzj.root:slWnqaS2ilBHBfHl"
    "@gateway01.us-west-2.prod.aws.tidbcloud.com:4000/"
    "spotify_db"
    "?ssl_verify_cert=false&ssl_verify_identity=false"
)

engine = create_engine(
    DATABASE_URL
)

In [30]:
engine = create_engine(
    DATABASE_URL
)

In [31]:
print('Conexión creada correctamente')

Conexión creada correctamente

In [32]:
with engine.connect() as conn:
    print("Conexión OK")

Conexión OK

In [43]:
# Leer los IDs de los artistas que ya existen en la base de datos
with engine.connect() as conn:
    existing_artists = pd.read_sql("SELECT artist_id FROM artists", conn)
    existing_artist_ids = existing_artists['artist_id'].tolist()

# Filtrar el DataFrame para obtener solo los nuevos artistas
new_artists = artists_clean[~artists_clean['artist_id'].isin(existing_artist_ids)]

# Insertar solo los nuevos artistas
if not new_artists.empty:
    new_artists.to_sql(
        name='artists',
        con=engine,
        if_exists='append',
        index=False,
        chunksize=100,
        method='multi'
    )

In [45]:
print('Artists insertados correctamente')

Artists insertados correctamente

In [46]:
# Leer los IDs de las canciones que ya existen en la base de datos
with engine.connect() as conn:
    existing_tracks = pd.read_sql("SELECT track_id FROM tracks", conn)
    existing_track_ids = existing_tracks['track_id'].tolist()

# Filtrar el DataFrame para obtener solo las nuevas canciones
new_tracks = tracks_clean[~tracks_clean['track_id'].isin(existing_track_ids)]

# Insertar solo las nuevas canciones
if not new_tracks.empty:
    new_tracks.to_sql(
        name='tracks',
        con=engine,
        if_exists='append',
        index=False,
        chunksize=100,
        method='multi'
    )

DatabaseError: Execution failed on sql 'INSERT INTO tracks (track_id, track_name, artist_id, release_year, popularity, danceability, energy, valence, acousticness, duration_ms, tempo) VALUES (:track_id_m0, :track_name_m0, :artist_id_m0, :release_year_m0, :popularity_m0, :danceability_m0, :energy_m0, :valence_m0, :acousticness_m0, :duration_ms_m0, :tempo_m0), (:track_id_m1, :track_name_m1, :artist_id_m1, :release_year_m1, :popularity_m1, :danceability_m1, :energy_m1, :valence_m1, :acousticness_m1, :duration_ms_m1, :tempo_m1), (:track_id_m2, :track_name_m2, :artist_id_m2, :release_year_m2, :popularity_m2, :danceability_m2, :energy_m2, :valence_m2, :acousticness_m2, :duration_ms_m2, :tempo_m2), (:track_id_m3, :track_name_m3, :artist_id_m3, :release_year_m3, :popularity_m3, :danceability_m3, :energy_m3, :valence_m3, :acousticness_m3, :duration_ms_m3, :tempo_m3), (:track_id_m4, :track_name_m4, :artist_id_m4, :release_year_m4, :popularity_m4, :danceability_m4, :energy_m4, :valence_m4, :acousticness_m4, :duration_ms_m4, :tempo_m4), (:track_id_m5, :track_name_m5, :artist_id_m5, :release_year_m5, :popularity_m5, :danceability_m5, :energy_m5, :valence_m5, :acousticness_m5, :duration_ms_m5, :tempo_m5), (:track_id_m6, :track_name_m6, :artist_id_m6, :release_year_m6, :popularity_m6, :danceability_m6, :energy_m6, :valence_m6, :acousticness_m6, :duration_ms_m6, :tempo_m6), (:track_id_m7, :track_name_m7, :artist_id_m7, :release_year_m7, :popularity_m7, :danceability_m7, :energy_m7, :valence_m7, :acousticness_m7, :duration_ms_m7, :tempo_m7), (:track_id_m8, :track_name_m8, :artist_id_m8, :release_year_m8, :popularity_m8, :danceability_m8, :energy_m8, :valence_m8, :acousticness_m8, :duration_ms_m8, :tempo_m8), (:track_id_m9, :track_name_m9, :artist_id_m9, :release_year_m9, :popularity_m9, :danceability_m9, :energy_m9, :valence_m9, :acousticness_m9, :duration_ms_m9, :tempo_m9), (:track_id_m10, :track_name_m10, :artist_id_m10, :release_year_m10, :popularity_m10, :danceability_m10, :energy_m10, :valence_m10, :acousticness_m10, :duration_ms_m10, :tempo_m10), (:track_id_m11, :track_name_m11, :artist_id_m11, :release_year_m11, :popularity_m11, :danceability_m11, :energy_m11, :valence_m11, :acousticness_m11, :duration_ms_m11, :tempo_m11), (:track_id_m12, :track_name_m12, :artist_id_m12, :release_year_m12, :popularity_m12, :danceability_m12, :energy_m12, :valence_m12, :acousticness_m12, :duration_ms_m12, :tempo_m12), (:track_id_m13, :track_name_m13, :artist_id_m13, :release_year_m13, :popularity_m13, :danceability_m13, :energy_m13, :valence_m13, :acousticness_m13, :duration_ms_m13, :tempo_m13), (:track_id_m14, :track_name_m14, :artist_id_m14, :release_year_m14, :popularity_m14, :danceability_m14, :energy_m14, :valence_m14, :acousticness_m14, :duration_ms_m14, :tempo_m14), (:track_id_m15, :track_name_m15, :artist_id_m15, :release_year_m15, :popularity_m15, :danceability_m15, :energy_m15, :valence_m15, :acousticness_m15, :duration_ms_m15, :tempo_m15), (:track_id_m16, :track_name_m16, :artist_id_m16, :release_year_m16, :popularity_m16, :danceability_m16, :energy_m16, :valence_m16, :acousticness_m16, :duration_ms_m16, :tempo_m16), (:track_id_m17, :track_name_m17, :artist_id_m17, :release_year_m17, :popularity_m17, :danceability_m17, :energy_m17, :valence_m17, :acousticness_m17, :duration_ms_m17, :tempo_m17), (:track_id_m18, :track_name_m18, :artist_id_m18, :release_year_m18, :popularity_m18, :danceability_m18, :energy_m18, :valence_m18, :acousticness_m18, :duration_ms_m18, :tempo_m18), (:track_id_m19, :track_name_m19, :artist_id_m19, :release_year_m19, :popularity_m19, :danceability_m19, :energy_m19, :valence_m19, :acousticness_m19, :duration_ms_m19, :tempo_m19), (:track_id_m20, :track_name_m20, :artist_id_m20, :release_year_m20, :popularity_m20, :danceability_m20, :energy_m20, :valence_m20, :acousticness_m20, :duration_ms_m20, :tempo_m20), (:track_id_m21, :track_name_m21, :artist_id_m21, :release_year_m21, :popularity_m21, :danceability_m21, :energy_m21, :valence_m21, :acousticness_m21, :duration_ms_m21, :tempo_m21), (:track_id_m22, :track_name_m22, :artist_id_m22, :release_year_m22, :popularity_m22, :danceability_m22, :energy_m22, :valence_m22, :acousticness_m22, :duration_ms_m22, :tempo_m22), (:track_id_m23, :track_name_m23, :artist_id_m23, :release_year_m23, :popularity_m23, :danceability_m23, :energy_m23, :valence_m23, :acousticness_m23, :duration_ms_m23, :tempo_m23), (:track_id_m24, :track_name_m24, :artist_id_m24, :release_year_m24, :popularity_m24, :danceability_m24, :energy_m24, :valence_m24, :acousticness_m24, :duration_ms_m24, :tempo_m24), (:track_id_m25, :track_name_m25, :artist_id_m25, :release_year_m25, :popularity_m25, :danceability_m25, :energy_m25, :valence_m25, :acousticness_m25, :duration_ms_m25, :tempo_m25), (:track_id_m26, :track_name_m26, :artist_id_m26, :release_year_m26, :popularity_m26, :danceability_m26, :energy_m26, :valence_m26, :acousticness_m26, :duration_ms_m26, :tempo_m26), (:track_id_m27, :track_name_m27, :artist_id_m27, :release_year_m27, :popularity_m27, :danceability_m27, :energy_m27, :valence_m27, :acousticness_m27, :duration_ms_m27, :tempo_m27), (:track_id_m28, :track_name_m28, :artist_id_m28, :release_year_m28, :popularity_m28, :danceability_m28, :energy_m28, :valence_m28, :acousticness_m28, :duration_ms_m28, :tempo_m28), (:track_id_m29, :track_name_m29, :artist_id_m29, :release_year_m29, :popularity_m29, :danceability_m29, :energy_m29, :valence_m29, :acousticness_m29, :duration_ms_m29, :tempo_m29), (:track_id_m30, :track_name_m30, :artist_id_m30, :release_year_m30, :popularity_m30, :danceability_m30, :energy_m30, :valence_m30, :acousticness_m30, :duration_ms_m30, :tempo_m30), (:track_id_m31, :track_name_m31, :artist_id_m31, :release_year_m31, :popularity_m31, :danceability_m31, :energy_m31, :valence_m31, :acousticness_m31, :duration_ms_m31, :tempo_m31), (:track_id_m32, :track_name_m32, :artist_id_m32, :release_year_m32, :popularity_m32, :danceability_m32, :energy_m32, :valence_m32, :acousticness_m32, :duration_ms_m32, :tempo_m32), (:track_id_m33, :track_name_m33, :artist_id_m33, :release_year_m33, :popularity_m33, :danceability_m33, :energy_m33, :valence_m33, :acousticness_m33, :duration_ms_m33, :tempo_m33), (:track_id_m34, :track_name_m34, :artist_id_m34, :release_year_m34, :popularity_m34, :danceability_m34, :energy_m34, :valence_m34, :acousticness_m34, :duration_ms_m34, :tempo_m34), (:track_id_m35, :track_name_m35, :artist_id_m35, :release_year_m35, :popularity_m35, :danceability_m35, :energy_m35, :valence_m35, :acousticness_m35, :duration_ms_m35, :tempo_m35), (:track_id_m36, :track_name_m36, :artist_id_m36, :release_year_m36, :popularity_m36, :danceability_m36, :energy_m36, :valence_m36, :acousticness_m36, :duration_ms_m36, :tempo_m36), (:track_id_m37, :track_name_m37, :artist_id_m37, :release_year_m37, :popularity_m37, :danceability_m37, :energy_m37, :valence_m37, :acousticness_m37, :duration_ms_m37, :tempo_m37), (:track_id_m38, :track_name_m38, :artist_id_m38, :release_year_m38, :popularity_m38, :danceability_m38, :energy_m38, :valence_m38, :acousticness_m38, :duration_ms_m38, :tempo_m38), (:track_id_m39, :track_name_m39, :artist_id_m39, :release_year_m39, :popularity_m39, :danceability_m39, :energy_m39, :valence_m39, :acousticness_m39, :duration_ms_m39, :tempo_m39), (:track_id_m40, :track_name_m40, :artist_id_m40, :release_year_m40, :popularity_m40, :danceability_m40, :energy_m40, :valence_m40, :acousticness_m40, :duration_ms_m40, :tempo_m40), (:track_id_m41, :track_name_m41, :artist_id_m41, :release_year_m41, :popularity_m41, :danceability_m41, :energy_m41, :valence_m41, :acousticness_m41, :duration_ms_m41, :tempo_m41), (:track_id_m42, :track_name_m42, :artist_id_m42, :release_year_m42, :popularity_m42, :danceability_m42, :energy_m42, :valence_m42, :acousticness_m42, :duration_ms_m42, :tempo_m42), (:track_id_m43, :track_name_m43, :artist_id_m43, :release_year_m43, :popularity_m43, :danceability_m43, :energy_m43, :valence_m43, :acousticness_m43, :duration_ms_m43, :tempo_m43), (:track_id_m44, :track_name_m44, :artist_id_m44, :release_year_m44, :popularity_m44, :danceability_m44, :energy_m44, :valence_m44, :acousticness_m44, :duration_ms_m44, :tempo_m44), (:track_id_m45, :track_name_m45, :artist_id_m45, :release_year_m45, :popularity_m45, :danceability_m45, :energy_m45, :valence_m45, :acousticness_m45, :duration_ms_m45, :tempo_m45), (:track_id_m46, :track_name_m46, :artist_id_m46, :release_year_m46, :popularity_m46, :danceability_m46, :energy_m46, :valence_m46, :acousticness_m46, :duration_ms_m46, :tempo_m46), (:track_id_m47, :track_name_m47, :artist_id_m47, :release_year_m47, :popularity_m47, :danceability_m47, :energy_m47, :valence_m47, :acousticness_m47, :duration_ms_m47, :tempo_m47), (:track_id_m48, :track_name_m48, :artist_id_m48, :release_year_m48, :popularity_m48, :danceability_m48, :energy_m48, :valence_m48, :acousticness_m48, :duration_ms_m48, :tempo_m48), (:track_id_m49, :track_name_m49, :artist_id_m49, :release_year_m49, :popularity_m49, :danceability_m49, :energy_m49, :valence_m49, :acousticness_m49, :duration_ms_m49, :tempo_m49), (:track_id_m50, :track_name_m50, :artist_id_m50, :release_year_m50, :popularity_m50, :danceability_m50, :energy_m50, :valence_m50, :acousticness_m50, :duration_ms_m50, :tempo_m50), (:track_id_m51, :track_name_m51, :artist_id_m51, :release_year_m51, :popularity_m51, :danceability_m51, :energy_m51, :valence_m51, :acousticness_m51, :duration_ms_m51, :tempo_m51), (:track_id_m52, :track_name_m52, :artist_id_m52, :release_year_m52, :popularity_m52, :danceability_m52, :energy_m52, :valence_m52, :acousticness_m52, :duration_ms_m52, :tempo_m52), (:track_id_m53, :track_name_m53, :artist_id_m53, :release_year_m53, :popularity_m53, :danceability_m53, :energy_m53, :valence_m53, :acousticness_m53, :duration_ms_m53, :tempo_m53), (:track_id_m54, :track_name_m54, :artist_id_m54, :release_year_m54, :popularity_m54, :danceability_m54, :energy_m54, :valence_m54, :acousticness_m54, :duration_ms_m54, :tempo_m54), (:track_id_m55, :track_name_m55, :artist_id_m55, :release_year_m55, :popularity_m55, :danceability_m55, :energy_m55, :valence_m55, :acousticness_m55, :duration_ms_m55, :tempo_m55), (:track_id_m56, :track_name_m56, :artist_id_m56, :release_year_m56, :popularity_m56, :danceability_m56, :energy_m56, :valence_m56, :acousticness_m56, :duration_ms_m56, :tempo_m56), (:track_id_m57, :track_name_m57, :artist_id_m57, :release_year_m57, :popularity_m57, :danceability_m57, :energy_m57, :valence_m57, :acousticness_m57, :duration_ms_m57, :tempo_m57), (:track_id_m58, :track_name_m58, :artist_id_m58, :release_year_m58, :popularity_m58, :danceability_m58, :energy_m58, :valence_m58, :acousticness_m58, :duration_ms_m58, :tempo_m58), (:track_id_m59, :track_name_m59, :artist_id_m59, :release_year_m59, :popularity_m59, :danceability_m59, :energy_m59, :valence_m59, :acousticness_m59, :duration_ms_m59, :tempo_m59), (:track_id_m60, :track_name_m60, :artist_id_m60, :release_year_m60, :popularity_m60, :danceability_m60, :energy_m60, :valence_m60, :acousticness_m60, :duration_ms_m60, :tempo_m60), (:track_id_m61, :track_name_m61, :artist_id_m61, :release_year_m61, :popularity_m61, :danceability_m61, :energy_m61, :valence_m61, :acousticness_m61, :duration_ms_m61, :tempo_m61), (:track_id_m62, :track_name_m62, :artist_id_m62, :release_year_m62, :popularity_m62, :danceability_m62, :energy_m62, :valence_m62, :acousticness_m62, :duration_ms_m62, :tempo_m62), (:track_id_m63, :track_name_m63, :artist_id_m63, :release_year_m63, :popularity_m63, :danceability_m63, :energy_m63, :valence_m63, :acousticness_m63, :duration_ms_m63, :tempo_m63), (:track_id_m64, :track_name_m64, :artist_id_m64, :release_year_m64, :popularity_m64, :danceability_m64, :energy_m64, :valence_m64, :acousticness_m64, :duration_ms_m64, :tempo_m64), (:track_id_m65, :track_name_m65, :artist_id_m65, :release_year_m65, :popularity_m65, :danceability_m65, :energy_m65, :valence_m65, :acousticness_m65, :duration_ms_m65, :tempo_m65), (:track_id_m66, :track_name_m66, :artist_id_m66, :release_year_m66, :popularity_m66, :danceability_m66, :energy_m66, :valence_m66, :acousticness_m66, :duration_ms_m66, :tempo_m66), (:track_id_m67, :track_name_m67, :artist_id_m67, :release_year_m67, :popularity_m67, :danceability_m67, :energy_m67, :valence_m67, :acousticness_m67, :duration_ms_m67, :tempo_m67), (:track_id_m68, :track_name_m68, :artist_id_m68, :release_year_m68, :popularity_m68, :danceability_m68, :energy_m68, :valence_m68, :acousticness_m68, :duration_ms_m68, :tempo_m68), (:track_id_m69, :track_name_m69, :artist_id_m69, :release_year_m69, :popularity_m69, :danceability_m69, :energy_m69, :valence_m69, :acousticness_m69, :duration_ms_m69, :tempo_m69), (:track_id_m70, :track_name_m70, :artist_id_m70, :release_year_m70, :popularity_m70, :danceability_m70, :energy_m70, :valence_m70, :acousticness_m70, :duration_ms_m70, :tempo_m70), (:track_id_m71, :track_name_m71, :artist_id_m71, :release_year_m71, :popularity_m71, :danceability_m71, :energy_m71, :valence_m71, :acousticness_m71, :duration_ms_m71, :tempo_m71), (:track_id_m72, :track_name_m72, :artist_id_m72, :release_year_m72, :popularity_m72, :danceability_m72, :energy_m72, :valence_m72, :acousticness_m72, :duration_ms_m72, :tempo_m72), (:track_id_m73, :track_name_m73, :artist_id_m73, :release_year_m73, :popularity_m73, :danceability_m73, :energy_m73, :valence_m73, :acousticness_m73, :duration_ms_m73, :tempo_m73), (:track_id_m74, :track_name_m74, :artist_id_m74, :release_year_m74, :popularity_m74, :danceability_m74, :energy_m74, :valence_m74, :acousticness_m74, :duration_ms_m74, :tempo_m74), (:track_id_m75, :track_name_m75, :artist_id_m75, :release_year_m75, :popularity_m75, :danceability_m75, :energy_m75, :valence_m75, :acousticness_m75, :duration_ms_m75, :tempo_m75), (:track_id_m76, :track_name_m76, :artist_id_m76, :release_year_m76, :popularity_m76, :danceability_m76, :energy_m76, :valence_m76, :acousticness_m76, :duration_ms_m76, :tempo_m76), (:track_id_m77, :track_name_m77, :artist_id_m77, :release_year_m77, :popularity_m77, :danceability_m77, :energy_m77, :valence_m77, :acousticness_m77, :duration_ms_m77, :tempo_m77), (:track_id_m78, :track_name_m78, :artist_id_m78, :release_year_m78, :popularity_m78, :danceability_m78, :energy_m78, :valence_m78, :acousticness_m78, :duration_ms_m78, :tempo_m78), (:track_id_m79, :track_name_m79, :artist_id_m79, :release_year_m79, :popularity_m79, :danceability_m79, :energy_m79, :valence_m79, :acousticness_m79, :duration_ms_m79, :tempo_m79), (:track_id_m80, :track_name_m80, :artist_id_m80, :release_year_m80, :popularity_m80, :danceability_m80, :energy_m80, :valence_m80, :acousticness_m80, :duration_ms_m80, :tempo_m80), (:track_id_m81, :track_name_m81, :artist_id_m81, :release_year_m81, :popularity_m81, :danceability_m81, :energy_m81, :valence_m81, :acousticness_m81, :duration_ms_m81, :tempo_m81), (:track_id_m82, :track_name_m82, :artist_id_m82, :release_year_m82, :popularity_m82, :danceability_m82, :energy_m82, :valence_m82, :acousticness_m82, :duration_ms_m82, :tempo_m82), (:track_id_m83, :track_name_m83, :artist_id_m83, :release_year_m83, :popularity_m83, :danceability_m83, :energy_m83, :valence_m83, :acousticness_m83, :duration_ms_m83, :tempo_m83), (:track_id_m84, :track_name_m84, :artist_id_m84, :release_year_m84, :popularity_m84, :danceability_m84, :energy_m84, :valence_m84, :acousticness_m84, :duration_ms_m84, :tempo_m84), (:track_id_m85, :track_name_m85, :artist_id_m85, :release_year_m85, :popularity_m85, :danceability_m85, :energy_m85, :valence_m85, :acousticness_m85, :duration_ms_m85, :tempo_m85), (:track_id_m86, :track_name_m86, :artist_id_m86, :release_year_m86, :popularity_m86, :danceability_m86, :energy_m86, :valence_m86, :acousticness_m86, :duration_ms_m86, :tempo_m86), (:track_id_m87, :track_name_m87, :artist_id_m87, :release_year_m87, :popularity_m87, :danceability_m87, :energy_m87, :valence_m87, :acousticness_m87, :duration_ms_m87, :tempo_m87), (:track_id_m88, :track_name_m88, :artist_id_m88, :release_year_m88, :popularity_m88, :danceability_m88, :energy_m88, :valence_m88, :acousticness_m88, :duration_ms_m88, :tempo_m88), (:track_id_m89, :track_name_m89, :artist_id_m89, :release_year_m89, :popularity_m89, :danceability_m89, :energy_m89, :valence_m89, :acousticness_m89, :duration_ms_m89, :tempo_m89), (:track_id_m90, :track_name_m90, :artist_id_m90, :release_year_m90, :popularity_m90, :danceability_m90, :energy_m90, :valence_m90, :acousticness_m90, :duration_ms_m90, :tempo_m90), (:track_id_m91, :track_name_m91, :artist_id_m91, :release_year_m91, :popularity_m91, :danceability_m91, :energy_m91, :valence_m91, :acousticness_m91, :duration_ms_m91, :tempo_m91), (:track_id_m92, :track_name_m92, :artist_id_m92, :release_year_m92, :popularity_m92, :danceability_m92, :energy_m92, :valence_m92, :acousticness_m92, :duration_ms_m92, :tempo_m92), (:track_id_m93, :track_name_m93, :artist_id_m93, :release_year_m93, :popularity_m93, :danceability_m93, :energy_m93, :valence_m93, :acousticness_m93, :duration_ms_m93, :tempo_m93), (:track_id_m94, :track_name_m94, :artist_id_m94, :release_year_m94, :popularity_m94, :danceability_m94, :energy_m94, :valence_m94, :acousticness_m94, :duration_ms_m94, :tempo_m94), (:track_id_m95, :track_name_m95, :artist_id_m95, :release_year_m95, :popularity_m95, :danceability_m95, :energy_m95, :valence_m95, :acousticness_m95, :duration_ms_m95, :tempo_m95), (:track_id_m96, :track_name_m96, :artist_id_m96, :release_year_m96, :popularity_m96, :danceability_m96, :energy_m96, :valence_m96, :acousticness_m96, :duration_ms_m96, :tempo_m96), (:track_id_m97, :track_name_m97, :artist_id_m97, :release_year_m97, :popularity_m97, :danceability_m97, :energy_m97, :valence_m97, :acousticness_m97, :duration_ms_m97, :tempo_m97), (:track_id_m98, :track_name_m98, :artist_id_m98, :release_year_m98, :popularity_m98, :danceability_m98, :energy_m98, :valence_m98, :acousticness_m98, :duration_ms_m98, :tempo_m98), (:track_id_m99, :track_name_m99, :artist_id_m99, :release_year_m99, :popularity_m99, :danceability_m99, :energy_m99, :valence_m99, :acousticness_m99, :duration_ms_m99, :tempo_m99)': (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`spotify_db`.`tracks`, CONSTRAINT `fk_1` FOREIGN KEY (`artist_id`) REFERENCES `artists` (`artist_id`))')